#!/bin/sh

cd buildbot_ndk
rm *.log
git pull
time PLATFORM=ndk ./libretro-buildbot-recipe.sh recipes/recipes-android | tee ndk-build.log
echo
echo

RA_DIR=$(pwd)/retroarch/android/
cd $RA_DIR
mkdir pkg
cd pkg

mkdir "$(date +%F)_cores" "$(date +%F)_cores"
cp -Rv ../../../dist/android/* "$(date +%F)_cores"
cp -v ../../../ndk-build.log "$(date +%F)_RetroArch.log"
cp -v ../phoenix/bin/retroarch-debug.apk "$(date +%F)_RetroArch.apk"
find . -type f -name '*.so' -exec zip '{}'.zip '{}' \;

rsync --progress * user@host:/home/buildbot/www/nightly/android/
cd
echo
echo

cd buildbot_x64
rm *.log
git pull
time ./libretro-buildbot-recipe.sh recipes/recipes.win-mingw64-seh | tee win-mingw64-seh-build.log
echo
echo
time ./libretro-buildbot-recipe.sh recipes/recipes.win-mingw64-sjlj | tee win-mingw64-sjlj-build.log
echo
echo

RA_DIR=$(pwd)/packages_x64/$(date +%F)_cores
mkdir $RA_DIR -p
cd $RA_DIR
cp -v ../../dist/win_x64/*.dll .
cp -v ../../dist/info/*.info .
cp -v ../../win-mingw64*.log .

7z u -mx9 "${RA_DIR}.7z" *
rsync --progress ../*.7z user@host:/home/buildbot/www/nightly/win-x86_64
cd
echo
echo

cd buildbot_x86
rm *.log
git pull
time ./libretro-buildbot-recipe.sh recipes/recipes.win-mingw32-dw2 | tee win-mingw32-dw2-build.log
echo
echo
time ./libretro-buildbot-recipe.sh recipes/recipes.win-mingw32-sjlj | tee win-mingw32-sjlj-build.log
echo
echo

RA_DIR=$(pwd)/packages_x86/$(date +%F)_cores
mkdir $RA_DIR -p
cd $RA_DIR
cp -v ../../dist/win_x86/*.dll .
cp -v ../../dist/info/*.info .
cp -v ../../win-mingw32*.log .

7z u -mx9 "${RA_DIR}.7z" *
rsync --progress ../*.7z user@host:/home/buildbot/www/nightly/win-x86
cd
echo
echo

cd buildbot_psp
rm *.log
git pull
time SUFFIX=_psp1 PLATFORM=psp1 ./libretro-buildbot-recipe.sh recipes/recipes.pspsdk | tee psp-build.log
echo
echo

RA_DIR=$(pwd)/retroarch/psp1/pkg/
cd $RA_DIR

cp -v ../../../dist/info/fceumm_libretro.info ../../../dist/info/fmsx_libretro.info ../../../dist/info/gambatte_libretro.info ../../../dist/info/mednafen_pce_fast_libretro.info ../../../dist/info/nxengine_libretro.info ../../../dist/info/prboom_libretro.info ../../../dist/info/tempgba_libretro.info ./cores/
cp -v ../../../psp*.log .

7z u -mx9 "$(date +%F)_RetroArch.7z" *
rsync --progress *.7z user@host:/home/buildbot/www/nightly/psp
cd 
echo
echo
