default: upgrade fetch build

upgrade:
	@./libretro-upgrade.sh

fetch:
	@./libretro-fetch.sh retroarch $(grep -Eo '^[^ ]+' ${BASE_DIR}/recipes/nintendo/libnx)

build:
	@./libretro-build-libnx.sh

.PHONY: default
