#!/bin/bash
WORKDIR=$PWD
### run this inside a libretro super clone


### ios cores

echo BUILDBOT TASK: packaging-cores
CORE_DIR=$PWD/ios_cores/$(date +%F)_cores
mkdir -p $CORE_DIR

cd $CORE_DIR
mkdir -p ../latest/

find ../../dist/ios -name '*.dylib' -mmin -1000 -exec cp '{}' ./ \;
find ./ -type f -name '*.dylib' -exec zip -j '{}'.zip '{}' \;
find ./ -type f -name '*.dylib' -exec rm -rv '{}' \;
find ./ -type f -name '*.zip' -exec cp -v '{}' ../latest/ \;

rsync -av ../* buildbot@bot.libretro.com:/home/buildbot/www/nightly/ios

cd $WORKDIR

### osx-x86_64 cores

echo BUILDBOT TASK: packaging-cores
CORE_DIR=$PWD/osx-x86_64_cores/$(date +%F)_cores
mkdir -p $CORE_DIR

cd $CORE_DIR
mkdir -p ../latest/

find ../../dist/osx-x86_64 -name '*.dylib' -mmin -1000 -exec cp '{}' ./ \;
find ./ -type f -name '*.dylib' -exec zip -j '{}'.zip '{}' \;
find ./ -type f -name '*.dylib' -exec rm -rv '{}' \;
find ./ -type f -name '*.zip' -exec cp -v '{}' ../latest/ \;

rsync -av ../* buildbot@bot.libretro.com:/home/buildbot/www/nightly/osx-x86_64

cd $WORKDIR
